#!/usr/bin/env python3
"""Validate Exhibit A Git and CI governance contract deterministically."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, TypedDict

CONTRACT_NAME = "git-ci-contract"

RULE_TITLES: dict[str, str] = {
    "GCC000": "CI configuration must exist in repository",
    "GCC001": "Conventional commits must be enforced with required types",
    "GCC002": "Branch naming policy must enforce feature/fix/refactor prefixes",
    "GCC003": "Force pushes to main must be forbidden",
    "GCC004": "Pull requests must be required for merges to main",
    "GCC005": "Active branch must match branch naming policy",
    "GCC010": "iOS CI must run SwiftLint",
    "GCC011": "iOS CI must build the project",
    "GCC012": "iOS CI must run unit tests",
    "GCC013": "iOS CI must run snapshot tests",
    "GCC020": "Backend CI must run mypy in strict mode",
    "GCC021": "Backend CI must run ruff check",
    "GCC022": "Backend CI must run ruff format --check",
    "GCC023": "Backend CI must run pytest with coverage gate >= 90%",
    "GCC030": "SwiftLint force_unwrapping must be error",
    "GCC031": "SwiftLint implicitly_unwrapped_optional must be error",
    "GCC032": "SwiftLint force_cast must be error",
    "GCC040": "CI must compare binary artifacts and alert on >10% growth",
    "GCC041": "Snapshot reference images must be committed",
    "GCC042": "CI must attach snapshot diff artifacts on failures",
    "GCC043": "CI must scan for AI attribution markers and fail on matches",
    "GCC044": "Repository must not contain AI attribution markers",
    "GCC045": "PR checklist must enforce tests, snapshot updates, and SwiftLint cleanliness",
    "GCC046": "CI lint/type/test steps must not use continue-on-error: true",
    "GCC047": "Quality gates must exist for iOS and backend pipelines",
}

IGNORED_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "venv",
    ".mypy_cache",
    ".pytest_cache",
    "__pycache__",
    "node_modules",
    "dist",
    "build",
    ".build",
    ".idea",
    ".vscode",
    ".tox",
    ".nox",
    ".claude",
}

TEXT_EXTENSIONS = {
    ".md",
    ".txt",
    ".py",
    ".swift",
    ".yml",
    ".yaml",
    ".json",
    ".toml",
    ".ini",
    ".cfg",
    ".sh",
    ".js",
    ".cjs",
    ".mjs",
    ".ts",
    ".tsx",
    ".jsx",
    ".rb",
    ".go",
    ".rs",
    ".java",
    ".kt",
    ".kts",
    ".c",
    ".cpp",
    ".h",
    ".hpp",
    ".m",
    ".mm",
    ".pbxproj",
}

ATTRIBUTION_PATTERNS = [
    re.compile(r"generated by (chatgpt|gpt-4|claude|copilot|openai)", re.IGNORECASE),
    re.compile(r"written by (chatgpt|claude|copilot|openai)", re.IGNORECASE),
    re.compile(r"created with (chatgpt|gpt-4|claude|copilot|openai)", re.IGNORECASE),
    re.compile(r"co-authored-by:\s*(chatgpt|claude|copilot|openai)", re.IGNORECASE),
]

GATE_KEYWORDS = (
    "swiftlint",
    "mypy",
    "ruff",
    "pytest",
    "xcodebuild",
    "snapshot",
    "unit test",
)

BRANCH_NAME_RE = re.compile(r"^(feature|fix|refactor)/[a-z0-9._-]+$")
SNAPSHOT_IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".heic", ".pdf"}


@dataclass(frozen=True)
class Violation:
    """Single deterministic contract violation."""

    rule_id: str
    title: str
    rejection: str
    file: str
    line: int
    snippet: str

    def as_dict(self) -> ViolationOutput:
        return {
            "rule_id": self.rule_id,
            "title": self.title,
            "rejection": self.rejection,
            "file": self.file,
            "line": self.line,
            "snippet": self.snippet,
        }


class SummaryOutput(TypedDict):
    files_scanned: int
    rules_checked: int
    violations: int


class ViolationOutput(TypedDict):
    rule_id: str
    title: str
    rejection: str
    file: str
    line: int
    snippet: str


class ResultOutput(TypedDict):
    contract: str
    verdict: Literal["PASS", "REJECT"]
    summary: SummaryOutput
    violations: list[ViolationOutput]


def _line_snippet(text: str) -> str:
    return text.strip()[:240]


def _line_number_from_offset(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def _is_policy_or_example_line(line: str) -> bool:
    lower = line.lower()
    mentions_attribution = any(
        token in lower
        for token in ("generated by", "written by", "created with", "co-authored-by")
    )
    if not mentions_attribution:
        return False

    policy_context = any(
        token in lower
        for token in ("denylist", "marker", "policy", "scan", "scanner", "grep", "rg ")
    )
    list_context = lower.strip().startswith("-") and '"' in line and "," in line
    stripped = line.strip()
    quoted_example = (
        ("generated by" in lower or "written by" in lower or "created with" in lower)
        and stripped.startswith('"')
        and stripped.endswith('"')
    )
    return policy_context or list_context or quoted_example


class ContractValidator:
    """Deterministic validator for Git + CI governance contract."""

    def __init__(self, root: Path):
        self.root = root.resolve()
        self.violations: list[Violation] = []
        self._seen: set[tuple[str, str, int, str]] = set()
        self._cache: dict[Path, str] = {}

        self.workflow_files = self._collect_workflow_files()
        self.governance_files = self._collect_governance_files()
        self.commitlint_files = self._collect_commitlint_files()
        self.swiftlint_files = self._collect_swiftlint_files()
        self.pr_template_files = self._collect_pr_template_files()
        self.snapshot_reference_images = self._collect_snapshot_reference_images()
        self.repo_text_files = self._collect_repo_text_files()

        self.ios_workflows, self.backend_workflows = self._classify_workflows()

        scanned = set(self.workflow_files)
        scanned.update(self.governance_files)
        scanned.update(self.commitlint_files)
        scanned.update(self.swiftlint_files)
        scanned.update(self.pr_template_files)
        scanned.update(self.repo_text_files)
        self.files_scanned = len(scanned)

    def _is_ignored(self, path: Path) -> bool:
        return any(part in IGNORED_DIRS for part in path.parts)

    def _relative(self, path: Path) -> str:
        try:
            return path.relative_to(self.root).as_posix()
        except ValueError:
            return path.as_posix()

    def _read_text(self, path: Path) -> str:
        if path in self._cache:
            return self._cache[path]
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except Exception:
            text = ""
        self._cache[path] = text
        return text

    def _add_violation(
        self,
        rule_id: str,
        file: str,
        line: int,
        snippet: str,
        detail: str,
    ) -> None:
        title = RULE_TITLES[rule_id]
        key = (rule_id, file, line, detail)
        if key in self._seen:
            return
        self._seen.add(key)
        self.violations.append(
            Violation(
                rule_id=rule_id,
                title=title,
                rejection=f"REJECT: {detail}",
                file=file,
                line=line,
                snippet=snippet,
            )
        )

    def _glob_existing(self, relative_pattern: str) -> list[Path]:
        return sorted(
            path for path in self.root.glob(relative_pattern) if path.is_file()
        )

    def _collect_workflow_files(self) -> list[Path]:
        files = self._glob_existing(".github/workflows/*.yml")
        files.extend(self._glob_existing(".github/workflows/*.yaml"))
        return sorted(set(files))

    def _collect_governance_files(self) -> list[Path]:
        files: list[Path] = []
        files.extend(self._glob_existing(".github/settings.yml"))
        files.extend(self._glob_existing(".github/settings.yaml"))
        files.extend(self._glob_existing(".github/rulesets/*.json"))
        files.extend(self._glob_existing(".github/rulesets/*.yml"))
        files.extend(self._glob_existing(".github/rulesets/*.yaml"))
        files.extend(self._glob_existing(".github/policies/*.yml"))
        files.extend(self._glob_existing(".github/policies/*.yaml"))
        files.extend(self._glob_existing(".github/policies/*.json"))
        return sorted(set(files))

    def _collect_commitlint_files(self) -> list[Path]:
        patterns = [
            "commitlint.config.js",
            "commitlint.config.cjs",
            "commitlint.config.mjs",
            "commitlint.config.ts",
            ".commitlintrc",
            ".commitlintrc.json",
            ".commitlintrc.yml",
            ".commitlintrc.yaml",
            ".commitlintrc.js",
            ".commitlintrc.cjs",
        ]
        files: list[Path] = []
        for pattern in patterns:
            files.extend(self._glob_existing(pattern))
        return sorted(set(files))

    def _collect_swiftlint_files(self) -> list[Path]:
        files: list[Path] = []
        files.extend(self._glob_existing(".swiftlint.yml"))
        files.extend(self._glob_existing(".swiftlint.yaml"))
        return sorted(set(files))

    def _collect_pr_template_files(self) -> list[Path]:
        files: list[Path] = []
        files.extend(self._glob_existing(".github/pull_request_template.md"))
        files.extend(self._glob_existing(".github/PULL_REQUEST_TEMPLATE/*.md"))
        return sorted(set(files))

    def _collect_snapshot_reference_images(self) -> list[Path]:
        matches: list[Path] = []
        for path in self.root.rglob("*"):
            if not path.is_file() or self._is_ignored(path):
                continue
            if path.suffix.lower() not in SNAPSHOT_IMAGE_EXTS:
                continue
            normalized = path.as_posix().lower()
            if "__snapshots__" in normalized or "/referenceimages/" in normalized:
                matches.append(path)
        return sorted(set(matches))

    def _collect_repo_text_files(self) -> list[Path]:
        files: list[Path] = []
        for path in self.root.rglob("*"):
            if not path.is_file() or self._is_ignored(path):
                continue
            if path.suffix.lower() not in TEXT_EXTENSIONS:
                continue
            if path.stat().st_size > 1_000_000:
                continue
            files.append(path)
        return sorted(files)

    def _classify_workflows(self) -> tuple[list[Path], list[Path]]:
        ios: list[Path] = []
        backend: list[Path] = []
        for path in self.workflow_files:
            text = self._read_text(path).lower()
            if any(
                token in text for token in ("xcodebuild", "swiftlint", "runs-on: macos")
            ):
                ios.append(path)
            if any(token in text for token in ("mypy", "ruff", "pytest", "python")):
                backend.append(path)
        return sorted(set(ios)), sorted(set(backend))

    def _combined_text(self, paths: list[Path]) -> str:
        return "\n".join(self._read_text(path) for path in paths)

    def _find_in_paths(
        self, paths: list[Path], pattern: re.Pattern[str]
    ) -> tuple[Path, re.Match[str]] | None:
        for path in paths:
            text = self._read_text(path)
            match = pattern.search(text)
            if match:
                return path, match
        return None

    def _check_ci_configuration_presence(self) -> None:
        if self.workflow_files:
            return
        self._add_violation(
            "GCC000",
            ".github/workflows",
            1,
            "",
            "Missing CI workflows directory or workflow YAML files.",
        )

    def _check_conventional_commits(self) -> None:
        required_types = ("feat", "fix", "refactor", "test", "docs", "chore")
        if not self.commitlint_files:
            self._add_violation(
                "GCC001",
                ".",
                1,
                "",
                "Missing commitlint configuration for conventional commit enforcement.",
            )
            return

        config_text = self._combined_text(self.commitlint_files)
        missing_types = [
            commit_type
            for commit_type in required_types
            if not re.search(rf"['\"]{commit_type}['\"]", config_text)
        ]
        if missing_types:
            self._add_violation(
                "GCC001",
                self._relative(self.commitlint_files[0]),
                1,
                _line_snippet(
                    self._read_text(self.commitlint_files[0]).splitlines()[0]
                    if self._read_text(self.commitlint_files[0]).splitlines()
                    else ""
                ),
                f"Commitlint config missing required types: {', '.join(missing_types)}.",
            )
            return

        if "commitlint" not in self._combined_text(self.workflow_files).lower():
            self._add_violation(
                "GCC001",
                ".github/workflows",
                1,
                "",
                "CI does not run commitlint, so conventional commit rules are not enforced.",
            )

    def _check_branch_naming_enforcement(self) -> None:
        candidate_files = sorted(set(self.workflow_files + self.governance_files))
        if not candidate_files:
            self._add_violation(
                "GCC002",
                ".github",
                1,
                "",
                "Missing branch policy configuration files.",
            )
            return

        text = self._combined_text(candidate_files).lower()
        has_all_prefixes = all(
            prefix in text for prefix in ("feature/", "fix/", "refactor/")
        )
        has_pattern = bool(
            re.search(r"\^\(feature\|fix\|refactor\)/", text)
            or re.search(r"\(feature\|fix\|refactor\)", text)
        )

        if not (has_all_prefixes or has_pattern):
            self._add_violation(
                "GCC002",
                self._relative(candidate_files[0]),
                1,
                "",
                "Branch naming policy does not encode feature/<name>, fix/<name>, refactor/<name>.",
            )

    def _current_branch(self) -> str | None:
        head = self.root / ".git" / "HEAD"
        if not head.is_file():
            return None
        text = self._read_text(head).strip()
        if not text.startswith("ref:"):
            return None
        ref = text.split(":", 1)[1].strip()
        if not ref.startswith("refs/heads/"):
            return None
        return ref.removeprefix("refs/heads/")

    def _check_active_branch_name(self) -> None:
        branch = self._current_branch()
        if not branch or branch in {"main", "master"}:
            return
        if BRANCH_NAME_RE.fullmatch(branch):
            return
        self._add_violation(
            "GCC005",
            ".git/HEAD",
            1,
            branch,
            f"Active branch '{branch}' violates naming policy; expected feature/<name>, fix/<name>, or refactor/<name>.",
        )

    def _check_main_branch_protections(self) -> None:
        if not self.governance_files:
            self._add_violation(
                "GCC003",
                ".github",
                1,
                "",
                "Missing governance config for main branch protections.",
            )
            self._add_violation(
                "GCC004",
                ".github",
                1,
                "",
                "Missing governance config that requires pull requests for main branch merges.",
            )
            return

        text = self._combined_text(self.governance_files).lower()
        has_main_scope = "main" in text
        force_push_blocked = bool(
            re.search(r"allow_force_pushes\s*[:=]\s*false", text)
            or "non_fast_forward" in text
            or "block force pushes" in text
        )
        pr_required = bool(
            "required_pull_request_reviews" in text
            or "required_pull_request" in text
            or ("pull_request" in text and "required" in text)
        )

        if not has_main_scope or not force_push_blocked:
            self._add_violation(
                "GCC003",
                self._relative(self.governance_files[0]),
                1,
                "",
                "Main branch force-push prohibition is not explicitly configured.",
            )

        if not has_main_scope or not pr_required:
            self._add_violation(
                "GCC004",
                self._relative(self.governance_files[0]),
                1,
                "",
                "Main branch pull-request requirement is not explicitly configured.",
            )

    def _check_ios_pipeline(self) -> None:
        if not self.ios_workflows:
            self._add_violation(
                "GCC010",
                ".github/workflows",
                1,
                "",
                "No iOS workflow detected for SwiftLint/build/test gates.",
            )
            self._add_violation(
                "GCC011",
                ".github/workflows",
                1,
                "",
                "No iOS workflow detected for project build gate.",
            )
            self._add_violation(
                "GCC012",
                ".github/workflows",
                1,
                "",
                "No iOS workflow detected for unit-test gate.",
            )
            self._add_violation(
                "GCC013",
                ".github/workflows",
                1,
                "",
                "No iOS workflow detected for snapshot-test gate.",
            )
            return

        swiftlint_hit = self._find_in_paths(
            self.ios_workflows, re.compile(r"\bswiftlint\b", re.IGNORECASE)
        )
        if not swiftlint_hit:
            self._add_violation(
                "GCC010",
                self._relative(self.ios_workflows[0]),
                1,
                "",
                "iOS CI does not execute SwiftLint.",
            )

        build_hit = self._find_in_paths(
            self.ios_workflows, re.compile(r"xcodebuild[^\n]*\bbuild\b", re.IGNORECASE)
        )
        if not build_hit:
            self._add_violation(
                "GCC011",
                self._relative(self.ios_workflows[0]),
                1,
                "",
                "iOS CI does not execute a project build step.",
            )

        unit_test_hit = self._find_in_paths(
            self.ios_workflows, re.compile(r"xcodebuild[^\n]*\btest\b", re.IGNORECASE)
        )
        if not unit_test_hit:
            self._add_violation(
                "GCC012",
                self._relative(self.ios_workflows[0]),
                1,
                "",
                "iOS CI does not execute unit tests via xcodebuild test.",
            )

        snapshot_hit = self._find_in_paths(
            self.ios_workflows, re.compile(r"snapshot", re.IGNORECASE)
        )
        if not snapshot_hit:
            self._add_violation(
                "GCC013",
                self._relative(self.ios_workflows[0]),
                1,
                "",
                "iOS CI does not execute snapshot tests.",
            )

    def _mypy_has_strict_config(self) -> bool:
        config_candidates = [
            self.root / "mypy.ini",
            self.root / ".mypy.ini",
            self.root / "setup.cfg",
            self.root / "pyproject.toml",
        ]
        for path in config_candidates:
            if not path.is_file():
                continue
            text = self._read_text(path).lower()
            if re.search(r"^\s*strict\s*=\s*true\s*$", text, re.MULTILINE):
                return True
        return False

    def _coverage_gate_is_90_plus(self) -> bool:
        backend_text = self._combined_text(self.backend_workflows)
        for match in re.finditer(
            r"--cov-fail-under(?:=|\s+)(\d+(?:\.\d+)?)", backend_text
        ):
            if float(match.group(1)) >= 90.0:
                return True

        coverage_candidates = [
            self.root / ".coveragerc",
            self.root / "pyproject.toml",
            self.root / "setup.cfg",
        ]
        for path in coverage_candidates:
            if not path.is_file():
                continue
            text = self._read_text(path).lower()
            for match in re.finditer(r"fail_under\s*=\s*(\d+(?:\.\d+)?)", text):
                if float(match.group(1)) >= 90.0:
                    return True
        return False

    def _check_backend_pipeline(self) -> None:
        if not self.backend_workflows:
            self._add_violation(
                "GCC020",
                ".github/workflows",
                1,
                "",
                "No backend workflow detected for static analysis and test gates.",
            )
            self._add_violation(
                "GCC021",
                ".github/workflows",
                1,
                "",
                "No backend workflow detected for ruff checks.",
            )
            self._add_violation(
                "GCC022",
                ".github/workflows",
                1,
                "",
                "No backend workflow detected for ruff format check.",
            )
            self._add_violation(
                "GCC023",
                ".github/workflows",
                1,
                "",
                "No backend workflow detected for pytest coverage gate.",
            )
            return

        backend_text = self._combined_text(self.backend_workflows)
        mypy_has_strict_cmd = bool(
            re.search(r"\bmypy\b[^\n]*--strict\b", backend_text, re.IGNORECASE)
        )
        mypy_called = bool(re.search(r"\bmypy\b", backend_text, re.IGNORECASE))
        if not (
            mypy_has_strict_cmd or (mypy_called and self._mypy_has_strict_config())
        ):
            self._add_violation(
                "GCC020",
                self._relative(self.backend_workflows[0]),
                1,
                "",
                "Backend CI must run mypy with --strict or equivalent strict config.",
            )

        if not re.search(r"\bruff\b[^\n]*\bcheck\b", backend_text, re.IGNORECASE):
            self._add_violation(
                "GCC021",
                self._relative(self.backend_workflows[0]),
                1,
                "",
                "Backend CI must run ruff check.",
            )

        if not re.search(
            r"\bruff\b[^\n]*\bformat\b[^\n]*--check\b", backend_text, re.IGNORECASE
        ):
            self._add_violation(
                "GCC022",
                self._relative(self.backend_workflows[0]),
                1,
                "",
                "Backend CI must run ruff format --check.",
            )

        pytest_called = bool(re.search(r"\bpytest\b", backend_text, re.IGNORECASE))
        if not pytest_called or not self._coverage_gate_is_90_plus():
            self._add_violation(
                "GCC023",
                self._relative(self.backend_workflows[0]),
                1,
                "",
                "Backend CI must run pytest with coverage fail-under >= 90.",
            )

    def _swiftlint_rule_is_error(self, text: str, rule: str) -> bool:
        flat = re.compile(rf"^\s*{re.escape(rule)}\s*:\s*error\s*$", re.MULTILINE)
        block = re.compile(
            rf"{re.escape(rule)}\s*:\s*\n(?:[ \t].*\n)*?\s*severity\s*:\s*error\b",
            re.IGNORECASE,
        )
        return bool(flat.search(text) or block.search(text))

    def _check_swiftlint_rules(self) -> None:
        if not self.swiftlint_files:
            for rule_id, rule_name in (
                ("GCC030", "force_unwrapping"),
                ("GCC031", "implicitly_unwrapped_optional"),
                ("GCC032", "force_cast"),
            ):
                self._add_violation(
                    rule_id,
                    ".swiftlint.yml",
                    1,
                    "",
                    f"Missing SwiftLint config; cannot enforce {rule_name}=error.",
                )
            return

        lint_path = self.swiftlint_files[0]
        text = self._read_text(lint_path)
        checks = (
            ("GCC030", "force_unwrapping"),
            ("GCC031", "implicitly_unwrapped_optional"),
            ("GCC032", "force_cast"),
        )
        for rule_id, rule_name in checks:
            if self._swiftlint_rule_is_error(text, rule_name):
                continue
            line = 1
            match = re.search(rf"^\s*{re.escape(rule_name)}\s*:", text, re.MULTILINE)
            if match:
                line = _line_number_from_offset(text, match.start())
            self._add_violation(
                rule_id,
                self._relative(lint_path),
                line,
                rule_name,
                f"SwiftLint rule '{rule_name}' must be configured as severity error.",
            )

    def _check_binary_size_monitoring(self) -> None:
        if not self.ios_workflows:
            self._add_violation(
                "GCC040",
                ".github/workflows",
                1,
                "",
                "No iOS workflow exists to enforce binary size growth policy.",
            )
            return

        text = self._combined_text(self.ios_workflows).lower()
        has_upload = "upload-artifact" in text
        has_download = "download-artifact" in text
        has_compare = bool(
            re.search(
                r"(baseline|previous|base).*(size|bytes|kb|mb)|(size|bytes|kb|mb).*(baseline|previous|base)",
                text,
                re.DOTALL,
            )
        )
        has_threshold = bool(
            re.search(r"10\s*%|10 percent|0\.10\b|0\.1\b|1\.10\b|1\.1\b", text)
        )

        if has_upload and has_download and has_compare and has_threshold:
            return

        missing_parts: list[str] = []
        if not has_upload:
            missing_parts.append("upload-artifact step")
        if not has_download:
            missing_parts.append("download-artifact step")
        if not has_compare:
            missing_parts.append("baseline/current size comparison")
        if not has_threshold:
            missing_parts.append(">10% threshold check")

        self._add_violation(
            "GCC040",
            self._relative(self.ios_workflows[0]),
            1,
            "",
            f"Binary size monitoring incomplete: missing {', '.join(missing_parts)}.",
        )

    def _check_snapshot_discipline(self) -> None:
        if not self.snapshot_reference_images:
            self._add_violation(
                "GCC041",
                ".",
                1,
                "",
                "No committed snapshot reference images found under __Snapshots__ or ReferenceImages.",
            )

        if not self.ios_workflows:
            self._add_violation(
                "GCC042",
                ".github/workflows",
                1,
                "",
                "No iOS workflow exists to publish snapshot diff artifacts.",
            )
            return

        text = self._combined_text(self.ios_workflows).lower()
        has_upload = "upload-artifact" in text
        has_failure_condition = (
            "if: failure()" in text or "if: ${{ failure() }}" in text
        )
        has_snapshot = "snapshot" in text
        has_diff = "diff" in text

        if has_upload and has_failure_condition and has_snapshot and has_diff:
            return

        self._add_violation(
            "GCC042",
            self._relative(self.ios_workflows[0]),
            1,
            "",
            "CI must upload snapshot diff artifacts when snapshot tests fail (if: failure + upload-artifact + snapshot diff path).",
        )

    def _check_attribution_guard(self) -> None:
        if not self.workflow_files:
            self._add_violation(
                "GCC043",
                ".github/workflows",
                1,
                "",
                "No CI workflows found for attribution-marker scanning.",
            )
            return

        text = self._combined_text(self.workflow_files).lower()
        has_scan_command = bool(
            re.search(
                r"(rg|grep)[^\n]*(chatgpt|claude|copilot|openai|ai[-\s]?assisted|generated by ai)",
                text,
            )
        )
        has_failure_action = "exit 1" in text or "fail" in text

        if has_scan_command and has_failure_action:
            return

        self._add_violation(
            "GCC043",
            self._relative(self.workflow_files[0]),
            1,
            "",
            "CI must grep/rg for AI attribution markers and fail the job on matches.",
        )

    def _check_repo_for_attribution_markers(self) -> None:
        for path in self.repo_text_files:
            relative = self._relative(path)
            if relative.startswith(".github/"):
                continue
            if "attribution" in relative.lower() or "denylist" in relative.lower():
                continue

            text = self._read_text(path)
            for line_number, line in enumerate(text.splitlines(), start=1):
                if _is_policy_or_example_line(line):
                    continue
                for pattern in ATTRIBUTION_PATTERNS:
                    if not pattern.search(line):
                        continue
                    self._add_violation(
                        "GCC044",
                        relative,
                        line_number,
                        _line_snippet(line),
                        "Repository contains an AI attribution marker; remove marker text from tracked files.",
                    )
                    break
                if any(
                    v.rule_id == "GCC044" and v.file == relative
                    for v in self.violations
                ):
                    break

    def _check_pr_template(self) -> None:
        if not self.pr_template_files:
            self._add_violation(
                "GCC045",
                ".github/pull_request_template.md",
                1,
                "",
                "Missing PR checklist template.",
            )
            return

        text = self._combined_text(self.pr_template_files).lower()
        missing_items: list[str] = []
        if not re.search(r"test.*pass|pass.*test", text):
            missing_items.append("tests must pass")
        if not (
            "snapshot" in text
            and ("ui" in text or "user interface" in text)
            and ("update" in text or "updated" in text)
        ):
            missing_items.append("snapshots updated when UI changes")
        if not (
            "swiftlint" in text
            and ("no " in text or "zero" in text)
            and "violation" in text
        ):
            missing_items.append("no SwiftLint violations")

        if not missing_items:
            return

        self._add_violation(
            "GCC045",
            self._relative(self.pr_template_files[0]),
            1,
            "",
            f"PR checklist missing required items: {', '.join(missing_items)}.",
        )

    def _check_continue_on_error(self) -> None:
        for path in self.workflow_files:
            text = self._read_text(path)
            lines = text.splitlines()
            for index, line in enumerate(lines):
                if "continue-on-error: true" not in line.lower():
                    continue
                window_start = max(0, index - 8)
                window_end = min(len(lines), index + 5)
                context = "\n".join(lines[window_start:window_end]).lower()
                if not any(keyword in context for keyword in GATE_KEYWORDS):
                    continue
                self._add_violation(
                    "GCC046",
                    self._relative(path),
                    index + 1,
                    _line_snippet(line),
                    "Quality gate step uses continue-on-error: true; CI must fail on lint/type/test violations.",
                )

    def _check_dual_pipeline_quality_gates(self) -> None:
        if self.ios_workflows and self.backend_workflows:
            return
        missing = []
        if not self.ios_workflows:
            missing.append("iOS pipeline")
        if not self.backend_workflows:
            missing.append("backend pipeline")
        self._add_violation(
            "GCC047",
            ".github/workflows",
            1,
            "",
            f"Missing required quality-gate pipeline(s): {', '.join(missing)}.",
        )

    def run(self) -> ResultOutput:
        self._check_ci_configuration_presence()
        self._check_conventional_commits()
        self._check_branch_naming_enforcement()
        self._check_main_branch_protections()
        self._check_active_branch_name()
        self._check_dual_pipeline_quality_gates()
        self._check_ios_pipeline()
        self._check_backend_pipeline()
        self._check_swiftlint_rules()
        self._check_binary_size_monitoring()
        self._check_snapshot_discipline()
        self._check_attribution_guard()
        self._check_repo_for_attribution_markers()
        self._check_pr_template()
        self._check_continue_on_error()

        violations_sorted = sorted(
            self.violations,
            key=lambda item: (item.rule_id, item.file, item.line, item.snippet),
        )
        verdict: Literal["PASS", "REJECT"] = (
            "PASS" if not violations_sorted else "REJECT"
        )
        return {
            "contract": CONTRACT_NAME,
            "verdict": verdict,
            "summary": {
                "files_scanned": self.files_scanned,
                "rules_checked": len(RULE_TITLES),
                "violations": len(violations_sorted),
            },
            "violations": [violation.as_dict() for violation in violations_sorted],
        }


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate git-ci contract.")
    parser.add_argument("--root", default=".", help="Repository root path (default: .)")
    parser.add_argument(
        "--format",
        default="json",
        choices=("json", "text"),
        help="Output format",
    )
    return parser.parse_args(argv)


def render_text(result: ResultOutput) -> str:
    lines = [
        f"contract: {result['contract']}",
        f"verdict: {result['verdict']}",
        f"files_scanned: {result['summary']['files_scanned']}",
        f"rules_checked: {result['summary']['rules_checked']}",
        f"violations: {result['summary']['violations']}",
    ]
    if result["violations"]:
        lines.append("")
        lines.append("Violations:")
        for violation in result["violations"]:
            lines.append(
                f"- {violation['rule_id']} {violation['file']}:{violation['line']} {violation['rejection']}"
            )
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    validator = ContractValidator(Path(args.root))
    result = validator.run()

    if args.format == "json":
        print(json.dumps(result, indent=2))
    else:
        print(render_text(result))

    return 0 if result["verdict"] == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
